export const LOADING_START = 'LOADING_START';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const LOADING_FAIL = 'LOADING_FAIL';

export const LOADING_NAMES_START = 'LOADING_NAMES_START';
export const LOADING_NAMES_SUCCESS = 'LOADING_NAMES_SUCCESS';
export const LOADING_NAMES_FAIL = 'LOADING_NAMES_FAIL';

export const REMOVE_ITEM_START = 'REMOVE_ITEM_START';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';

export const ADD_ITEM_START = 'ADD_ITEM_START';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';

export const SET_ITEMS = 'SET_ITEMS';
